version: '3'

services:
    db:
        build: Legendarios-db
        volumes:
            - ~/data/postgresql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    web:
        build:
            context: Legendarios-web
        command: ['./startup_cmds.sh']
        env_file:
            - .env
        volumes:
            - ./Legendarios-web/registros:/code/registros
        ports:
            - "8000:8000"
        links:
            - db:db
        depends_on:
            - db
