# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20170613_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='congregacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
