# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20170623_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='facebook_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='miembro',
            name='instagram_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='miembro',
            name='twitter_link',
            field=models.URLField(default=''),
        ),
    ]
