# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_auto_20170625_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legado',
            name='tipo',
            field=models.CharField(choices=[(b'Osos', b'Osos'), (b'Jaguares', b'Jaguares'), (b'\xc3\x81guilas', b'\xc3\x81guilas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='rol',
            field=models.CharField(choices=[(b'Participante', b'Participante'), (b'Coordinaci\xc3\xb3n', b'Coordinaci\xc3\xb3n'), (b'Sub Coordinaci\xc3\xb3n', b'Sub Coordinaci\xc3\xb3n'), (b'Administraci\xc3\xb3n', b'Administraci\xc3\xb3n'), (b'Jefe de Tribu', b'Jefe de Tribu'), (b'Voz', b'Voz'), (b'Log\xc3\xadstica', b'Log\xc3\xadstica'), (b'Evento', b'Evento'), (b'Seguridad', b'Seguridad'), (b'Apoyo', b'Apoyo')], max_length=50),
        ),
    ]
