# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_auto_20170728_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b'miembros/'),
        ),
    ]
