# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacion',
            options={'verbose_name_plural': 'Participaciones'},
        ),
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(upload_to='miembros/'),
        ),
    ]
