# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_miembro_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=25),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(null=True, upload_to='miembros/'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_de_legendario',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='pais',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='testimonio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_de_sangre',
            field=models.CharField(default='', max_length=25),
        ),
    ]
