# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_miembro_congregacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='numero_de_legendario',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
