# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_auto_20170625_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='facebook_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='instagram_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
